-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpqTK5KcemmeCMDad
1VgO76/ffZHDzJIAo7m5Je4AseqgCgYIKoZIzj0DAQehRANCAASx5VVhlbZVhVtY
kctoCb4QmLY3ZUJmgLDtCNsvVdWRXkKfSSmtwQGqZtPErCtRPOdqaCHy2jUDP5QU
l4o5V4Kk
-----END PRIVATE KEY-----