
const DEVICE_TOKEN = 'DEVICE_TOKEN';
const DEVICE_ID = 'DEVICE_ID';
const DEVICE_CONNECTION = 'DEVICE_CONNECTION';
const HAS_SESSION = 'HAS_SESSION';
const USER_DETAIL = 'USER_DETAIL';
const GUEST = 'GUEST';
const USER_TYPE = 'USER_TYPE';
const LOGIN_USER_TYPE = 'LOGIN_USER_TYPE';
const CONTACT_REASONS = 'CONTACT_REASONS';
const INFOGRAPHICS = 'INFOGRAPHICS';
const SELECTED_IMAGE = 'SELECTED_IMAGE';
const CART_COUNT = 'CART_COUNT';
const LOGOUT = 'LOGOUT';


export {
  //
  HAS_SESSION,
  LOGOUT,
  USER_DETAIL,
  DEVICE_TOKEN,
  DEVICE_ID,
  GUEST,
  USER_TYPE,
  CONTACT_REASONS,
  LOGIN_USER_TYPE,
  DEVICE_CONNECTION,
  SELECTED_IMAGE,
  INFOGRAPHICS,
  CART_COUNT
  //

};
